services:
  dir-api-server:
    image: ghcr.io/agntcy/dir-apiserver:v0.6.0
    env_file:
      - ./configs/dir/apiserver.env
    ports:
      - 8888:8888
      - 8889:8889
    depends_on:
      - zot
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    # # No healthcheck: production image is distroless and does not have wget/curl/nc or shells. Also, the endpoint at 8888 is only gRPC, not HTTP. The endpoint at 8889 does not exist.
    # # Future healthcheck via grpc-health-probe on 8888 when newer releases of dir-apiserver bundle grpc-health-probe. Fix was merged in https://github.com/agntcy/dir/pull/1017.
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8889/healthz/ready || exit 1
    #   interval: 10s
    #   retries: 60
    #   start_period: 10s

  zot:
    image: ghcr.io/project-zot/zot:v2.1.10
    ports:
      - 5555:5000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    # # No healthcheck: production image is distroless and does not have wget/curl/nc or shells.
    # # Note: Zot has a /readyz endpoint (Kubernetes compliant API) since v2.1.6 that can be used for healthchecks.
    # # Notes for /readyz: https://zotregistry.dev/v2.1.14/general/whats-new/#v216 and https://kubernetes.io/docs/reference/using-api/health-checks/
    # healthcheck:
    #   test: curl -f http://localhost:5000/v2/ || exit 1
    #   interval: 5s
    #   retries: 60
    #   start_period: 15s

  recruiter-agent:
    build:
      context: ../../../..
      dockerfile: coffeeAGNTCY/coffee_agents/recruiter/Dockerfile
    container_name: recruiter-agent
    ports:
      - "8881:8881"
    env_file:
      - ../.env
    environment:
      - ENABLE_HTTP=true
      - MCP_CONNECTION_MODE=binary
      - DIRECTORY_CLIENT_SERVER_ADDRESS=dir-api-server:8888
      - DIRECTORY_CLIENT_TLS_SKIP_VERIFY=true
      - OASF_API_VALIDATION_SCHEMA_URL=https://schema.oasf.outshift.com
    depends_on:
      - dir-api-server
    healthcheck:
      test: curl -f http://localhost:8881/.well-known/agent.json || exit 1
      interval: 10s
      retries: 30
      start_period: 30s
