name: Fake Build and Push All Docker Images

on:
  push:
    branches: [ghi223/test01, ghi223/test03-*]
    tags: ["test-tag-*"]
    paths:
      - 'coffeeAGNTCY/coffee_agents/**'
      - '!coffeeAGNTCY/coffee_agents/*/deployment/helm/**'
  pull_request:
    branches: [ghi223/*]
    paths:
      - 'coffeeAGNTCY/coffee_agents/**'
      - '!coffeeAGNTCY/coffee_agents/*/deployment/helm/**'
  workflow_dispatch:
    inputs:
      push:
        description: 'Whether to push the container images to the registry.'
        required: false
        type: boolean
        default: false
      build_corto:
        description: 'Whether to build the corto container images.'
        required: false
        type: boolean
        default: true
      build_lungo:
        description: 'Whether to build the lungo container images.'
        required: false
        type: boolean
        default: true
      build_recruiter:
        description: 'Whether to build the recruiter container images.'
        required: false
        type: boolean
        default: true
      image_tag:
        description: 'The tag to use for the container images.'
        required: false
        type: string
        default: ''

env:
  CORTO_DIR: coffeeAGNTCY/coffee_agents/corto
  LUNGO_DIR: coffeeAGNTCY/coffee_agents/lungo
  RECRUITER_DIR: coffeeAGNTCY/coffee_agents/recruiter

jobs:
  subprojects-to-build:
    runs-on: ubuntu-latest
    outputs:
      build_corto: ${{ steps.check-subprojects.outputs.build_corto }}
      build_lungo: ${{ steps.check-subprojects.outputs.build_lungo }}
      build_recruiter: ${{ steps.check-subprojects.outputs.build_recruiter }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Log event info
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"
      
      - name: Log relevant dispatch inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "build_corto=${{ inputs.build_corto }}"
          echo "build_lungo=${{ inputs.build_lungo }}"
          echo "build_recruiter=${{ inputs.build_recruiter }}"

      - name: Detect changed paths for main sub-projects
        id: check-subprojects
        run: |
          build_corto=false
          build_lungo=false
          build_recruiter=false

          if [[ "${{ github.event_name }}" == "push" ]]; then
            build_corto=true
            build_lungo=true
            build_recruiter=true
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            build_corto=${{ inputs.build_corto }}
            build_lungo=${{ inputs.build_lungo }}
            build_recruiter=${{ inputs.build_recruiter }}
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base="${{ github.event.pull_request.base.sha }}"
            head="${{ github.event.pull_request.head.sha }}"

            # Returns 0 if dir has changes, 1 if no changes
            dir_has_changes() (
              local base=$1 head=$2 dir=$3
              set -x # This option only lives in the subshell of this function because the function is defined with () instead of {}.
              ! git diff --name-only --exit-code --ignore-blank-lines $base $head "$dir"
            )
            dir_has_changes $base $head "$CORTO_DIR" && build_corto=true || build_corto=false
            dir_has_changes $base $head "$LUNGO_DIR" && build_lungo=true || build_lungo=false
            dir_has_changes $base $head "$RECRUITER_DIR" && build_recruiter=true || build_recruiter=false
          fi

          echo "build_corto=$build_corto" | tee -a $GITHUB_OUTPUT
          echo "build_lungo=$build_lungo" | tee -a $GITHUB_OUTPUT
          echo "build_recruiter=$build_recruiter" | tee -a $GITHUB_OUTPUT

  compute-build-parameters:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ steps.build_params.outputs.push}}
      image_tag: ${{ steps.build_params.outputs.image_tag }}
      git_branch: ${{ steps.build_params.outputs.git_branch }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Log event info
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"

      - name: Log relevant dispatch inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "push=${{ inputs.push }}"
          echo "image_tag=${{ inputs.image_tag }}"

      - name: Compute build parameters
        id: build_params
        run: |
          # default values
          push=false
          image_tag=unknown
          git_branch=${{ github.ref_name }}

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            image_tag=pr-${{ github.event.pull_request.number }}
            git_branch=${{ github.head_ref }}
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            push=true
            image_tag=latest
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            push=true
            image_tag=${{ github.ref_name }}
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            push=${{ inputs.push }}
            if [[ "${{ inputs.image_tag }}" != "" ]]; then
              image_tag=${{ inputs.image_tag }}
            else
              short_sha=${GITHUB_SHA:0:7}
              image_tag="dispatch_${short_sha}_run-${{ github.run_number }}" # informative default tag (though not unique)
            fi
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/heads/ghi223/* ]]; then
            push=true
            image_tag="ghi223-${GITHUB_SHA:0:7}"
          fi

          echo "push=$push" | tee -a $GITHUB_OUTPUT
          echo "image_tag=$image_tag" | tee -a $GITHUB_OUTPUT
          echo "git_branch=$git_branch" | tee -a $GITHUB_OUTPUT


  docker-build-corto:
    needs: [subprojects-to-build, compute-build-parameters]
    if: ${{ needs.subprojects-to-build.outputs.build_corto == 'true' }}
    strategy:
      matrix:
        image:
          - name: corto-ui
            dockerfile: coffeeAGNTCY/coffee_agents/corto/docker/Dockerfile.ui
    permissions: # permissions can only be maintained or reduced (not elevated) throughout a chain of workflows
      packages: write
      contents: read
    uses: ./.github/workflows/fake01-reusable-docker.yaml
    with: &docker-build-common-inputs
      name: ${{ matrix.image.name }}
      dockerfile: ${{ matrix.image.dockerfile }}
      push: ${{ needs.compute-build-parameters.outputs.push == 'true' }}
      platforms: linux/amd64,linux/arm64
      image_tag: ${{ needs.compute-build-parameters.outputs.image_tag }}
      git_branch: ${{ needs.compute-build-parameters.outputs.git_branch }}

  docker-build-lungo:
    needs: [subprojects-to-build, compute-build-parameters]
    if: ${{ needs.subprojects-to-build.outputs.build_lungo == 'true' }}
    strategy:
      matrix:
        image:
          - name: lungo-ui
            dockerfile: coffeeAGNTCY/coffee_agents/lungo/docker/Dockerfile.ui
    permissions: # permissions can only be maintained or reduced (not elevated) throughout a chain of workflows
      packages: write
      contents: read
    uses: ./.github/workflows/fake01-reusable-docker.yaml
    with: *docker-build-common-inputs

  docker-build-recruiter:
    needs: [subprojects-to-build, compute-build-parameters]
    if: ${{ needs.subprojects-to-build.outputs.build_recruiter == 'true' }}
    strategy:
      matrix:
        image:
          - name: recruiter
            dockerfile: coffeeAGNTCY/coffee_agents/recruiter/Dockerfile
    permissions: # permissions can only be maintained or reduced (not elevated) throughout a chain of workflows
      packages: write
      contents: read
    uses: ./.github/workflows/fake01-reusable-docker.yaml
    with: *docker-build-common-inputs
